### ISSUE TITLE
./toolchain.py build ivy error on  OS X 10.10.5 with Xcode 7

### ISSUE THREAD

**Issue by foreverzhao** [kivy/kivy-ios#160]
ranlib libpython2.7.a
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython2.7.a(pymath.o) has no symbols
clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/gyzhao/kivy-ios/dist/lib  -o python.exe \
            Modules/python.o \
            libpython2.7.a -ldl  -framework CoreFoundation -L/Users/gyzhao/kivy-ios/dist/hostpython/lib -lz  
ld: warning: directory not found for option '-L/Users/gyzhao/kivy-ios/dist/hostpython/lib'
ld: in /Users/gyzhao/kivy-ios/dist/lib/libffi.a(ffi64_x86_64.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1224, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1040, in **init**
    getattr(self, args.command)()
  File "./toolchain.py", line 1064, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 933, in build_recipes
    recipe.execute()
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 556, in execute
    self.build_all()
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, _args, *_kwargs)
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 643, in build_all
    self.build(arch)
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, _args, *_kwargs)
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 630, in build
    self.build_arch(arch)
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 678, in build_arch
    getattr(self, build)()
  File "/Users/gyzhao/kivy-ios/recipes/hostpython/__init__.py", line 68, in build_i386
    _env=build_env)
  File "/Users/gyzhao/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(_args, *_kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -C /Users/gyzhao/kivy-ios/build/hostpython/i386/Python-2.7.1 -j4 python.exe Parser/pgen'

  STDOUT:
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1285: warning: ignoring old commands for target`Modules/posixmodule.o'
Makefile:1394: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1286: warning: ignoring old commands for target`Modules/posixmodule.so'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1287: warning: ignoring old commands for target`Modules/errnomodule.o'
Makefile:1396: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1288: warning: ignoring old commands for target`Modules/errnomodule.so'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1289: warning: ignor... (75904 more, please see e.stdout)

  STDERR:
##

**Comment by spinningD20** [comment]
I have this issue as well, it's for compiling hostpython.  10.10.5 and XCode 7.  I also tried changing the recipe for hostpython to download another, more recent of python (2.7.5) to see if I could get that to do anything different, but it has the same error.

I've tried re-cloning, etc to make sure nothing went awry, it ends up the same.

I'm trying to get access to something older to see if it's related to that or not... this is my first time trying kivy-ios, following the directions on kivy.org, but I think it's a bug with newer environment, perhaps?

**Comment by spinningD20** [comment]
Good news for any that need this fixed immediately and don't know much about the internals of this process, downgrading to xcode 6.4 fixed this for me!

Find 6.4 for download in Apple developer section downloads, remove xcode 7 and install 6.4 from the downloaded dmg).

Now, why is it breaking with 7?  I have no idea.  Maybe when I understand more about this whole environment I can contribute further.  Good luck!

**Comment by Ramalus** [comment]
I've got this error. But this is not nearly closed. I'll try downgrading to xcode 6.x to see if that helps. But I'm guessing this really needs a bump.

**Comment by spinningD20** [comment]
Agreed, I wasn't trying to say it wasn't a bug, and it definitely needs fixed in order to make ios 9 apps.  I haven't had a chance to look into it myself yet, so hopefully someone will do so.

**Comment by jasoniem9246** [comment]
I got the same error on Xcode 7. error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by foreverzhao** [comment]
when do this bug fix

**Comment by jkamleh** [comment]
Same error OS X 10.11, Xcode 7

**Comment by D-Cipher** [comment]
I've tried 7 and 6.4 but still getting a similar error.

this is the error I get in 6.4:
ld: warning: directory not found for option '-F/Users/tingbochen/kivy-ios/dist/frameworks'
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame

**Comment by D-Cipher** [comment]
I had a lot problems with the build and I got it to work, I posted a guide to the build detailing some of the stumbling blocks I found here:
https://goo.gl/swR2L5

**Comment by Zen-CODE** [comment]
I think this merge fixes these issues: https://github.com/kivy/kivy-ios/commit/01a0c6a751f973a7c3bdd1c4d1b2345bb8bb6bc8

Will be brave and close the ticket. If anyone still has this issue when updating, please re-open or create a new ticket.
